[package]
name = "pathfinder-serde"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
ethers = "1.0.2"
num-bigint = { version = "0.4.3", features = ["serde"] }
pathfinder-common = { path = "../common" }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
serde_with = "2.1.0"
stark_hash = { path = "../stark_hash" }

[dev-dependencies]
pretty_assertions = "1.3.0"
