[package]
name = "pathfinder-merkle-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bitvec = "0.20.4"
pathfinder-common = { path = "../common" }
pathfinder-storage = { path = "../storage" }
rand = "0.8"
rusqlite = { version = "0.28.0", features = ["bundled"] }
stark_curve = { path = "../stark_curve" }
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
starknet-gateway-types = { path = "../gateway-types" }

[dev-dependencies]
pretty_assertions = "1.3.0"
