[package]
name = "pathfinder-retry"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tokio-retry = "0.3.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "test-util"] }
