[package]
name = "starknet-gateway-types"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
ethers = "1.0.2"
pathfinder-common = { path = "../common" }
pathfinder-serde = { path = "../serde" }
reqwest = "0.11.13"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = { version = "1.0.89", features = ["arbitrary_precision", "raw_value"] }
serde_with = "2.1.0"
sha3 = "0.10"
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
thiserror = "1.0.37"
tokio = { workspace = true }

[dev-dependencies]
# Due to pathfinder_common::starkhash!() usage
starknet-gateway-test-fixtures = { path = "../gateway-test-fixtures" }
tokio = { workspace = true, features = ["macros", "test-util"] }
zstd = "0.12"
